local_backend:
  # when using a custom proxy server port
  url: "http://192.168.0.37:3000/api/v1"
  # when accessing the local site from
backend:
  name: github
  branch: master
  repo: WPRN/Yggdrasil
  base_url: https://85o05b11ri.execute-api.eu-west-2.amazonaws.com/
  auth_endpoint: "/dev/auth"
  cms_label_prefix: "IEA-Paris-CMS "
logo_url: https://wprn.org/wprn/icon.png
extension: md
format: yaml-frontmatter
# show_preview_links: false
locale: fr
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "_"
# local_backend: true
# local_backend:
#   url: http://localhost:8081/api/v1
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders
  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en
publish_mode: editorial_workflow
media_folder: "static"
site_domain: cms.netlify.com
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "pages" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    i18n: true
    sortable_fields:
      ["commit_date", "title", "commit_author", "language.en", "language.fr"]
    locales: [en, fr]
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: true }
      # - {label: "Featured Image", name: "thumbnail", widget: "image", required: false, i18n: true}
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number", i18n: true}
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "faq_en" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ English" # Used in the UI
    folder: "content/en/faq" # The path to the folder where the documents are stored
    sortable_fields:
      ["commit_date", "title", "commit_author", "language.en", "language.fr"]
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "faq_fr" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ French" # Used in the UI
    folder: "content/fr/faq" # The path to the folder where the documents are stored
    sortable_fields:
      ["commit_date", "title", "commit_author", "language.en", "language.fr"]
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "institutions" # Used in routes, e.g., /admin/collections/blog
    label: "Partner institutions" # Used in the UI
    folder: "content/institutions" # The path to the folder where the documents are stored
    sortable_fields: ["commit_date", "title", "commit_author"]
    media_folder: ""
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Color background",
          name: "color",
          widget: "color",
          allowInput: true,
          default: "#FFFFFF",
        }
      - {
          label: "URL",
          name: "url",
          widget: "string",
          pattern:
            [
              '^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=\]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~',
              "Please use a valid URL",
            ],
        }
      - { label: "Picture", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "resources" # Used in routes, e.g., /admin/collections/blog
    label: "Resources" # Used in the UI
    folder: "content/resources" # The path to the folder where the documents are stored
    sortable_fields: ["commit_date", "title", "commit_author"]
    media_folder: "static/resources"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - {
          label: "Youtube ID",
          name: "youtube",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "External URL resource",
          hint: "overrides files or youtube ids",
          name: "url",
          widget: "string",
          pattern:
            [
              '^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=\]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~',
              "Please use a valid URL",
            ],
        }
      - { label: "Picture", name: "image", widget: "image" }
      - {
          label: "file",
          name: "file",
          widget: "object",
          fields:
            [
              { name: "fr", widget: "file", label: "French version" },
              { name: "en", widget: "file", label: "English version" },
            ],
        }
  - name: "sab" # Used in routes, e.g., /admin/collections/blog
    label: "Scientific Advisory Board" # Used in the UI
    folder: "content/sab" # The path to the folder where the documents are stored
    sortable_fields: ["commit_date", "title", "commit_author"]
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Firstname", name: "firstname", widget: "string" }
      - { label: "Lastname", name: "lastname", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - {
          label: "Profile URL",
          name: "url",
          widget: "string",
          pattern:
            [
              '^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=\]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~',
              "Please use a valid URL",
            ],
        }
      - { label: "Picture", name: "picture", widget: "image", required: false }
  - name: pressroom
    label: Pressroom
    media_folder: "static/press_releases"
    files:
      - name: pressroom
        label: Pressroom
        file: content/pressroom.md
        # Enable i18n for this file.
        i18n: true
        fields:
          - {
              label: "Mediakit",
              name: "mediakit",
              widget: "object",
              fields:
                [
                  { name: "url", widget: "string", label: "URL" },
                  { name: "content", widget: "string", label: "Content" },
                  {
                    name: "title",
                    widget: "string",
                    label: "Name of the media kit",
                  },
                ],
            }
          - {
              label: "Contact",
              name: "contact",
              widget: "object",
              fields:
                [
                  { name: "email", widget: "string", label: "Email" },
                  {
                    name: "phone",
                    widget: "string",
                    label: "Telephone number",
                  },
                  {
                    name: "name",
                    widget: "string",
                    label: "Name of press contact",
                  },
                ],
            }
          - {
              label: "Press releases",
              name: "releases",
              widget: "list",
              field:
                {
                  name: release,
                  widget: object,
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Date, name: date, widget: date },
                      { label: File, name: file, widget: file },
                    ],
                },
            }
          - {
              label: "Press reviews",
              name: "reviews",
              widget: "list",
              field:
                {
                  name: review,
                  widget: object,
                  fields:
                    [
                      { label: Subtitle, name: subtitle, widget: string },
                      { label: From, name: from, widget: string },
                      { label: Link, name: link, widget: string },
                      { label: Date, name: date, widget: date },
                    ],
                },
            }
  - name: translations
    label: Translations
    extension: "json"
    editor:
      preview: false
    files:
      - file: "translations/en.json"
        label: "English"
        name: "english"
        fields:
          - { name: body, label: Body, widget: code }
      - file: "translations/fr.json"
        label: "French"
        name: "french"
        fields:
          - { name: body, label: Body, widget: code }
